import Head from "next/head";
import Intro from "~/components/intro";
import { useQuestions } from "~/hooks/useQuestions";

export default function Home() {
  const response = useQuestions();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro />
      </main>
    </>
  );
}
