import Head from "next/head";
import React from "react";
import { Form } from "~/components/Form";
import GGH from "../assets/ggh.svg";
import LocalChamp from "../assets/localChampions.svg";
import Intro from "~/components/intro";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Intro />
      </main>
    </>
  );
}
